### ISSUE TITLE
Fix blueprint deployment

### ISSUE THREAD

**Issue by zeramorphic** [leanprover-community/con-nf#4]
The CI currently crashes when attempting to build blueprints.

**Comment by zeramorphic** [comment]
Ready to close as soon as `gh-pages` is actually deployed somewhere.

**Comment by YaelDillies** [comment]
The website is now online and ugly.

**Comment by zeramorphic** [comment]
The website is now online and looks nice! Closed by f8393b014b060b9b650c05fc8f1cc65b0d5df7c6.
